# Generated by Django 5.0.3 on 2024-05-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
